HonsArtifact/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^info$',views.InfoPage.as_view(),name='info'),
    url(r'^work$',views.WorkPage.as_view(),name='work'),
    url(r'^contact$',views.ContactPage.as_view(),name='contact'),
    url(r'^SpeedApp/',include('SpeedApp.urls',namespace='SpeedApp')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SpeedApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'SpeedApp'

urlpatterns = [
    url(r'detect/$',views.DetectPageView.as_view(), name='detect'),
    url(r'calculate/(?P<pk>\d+)/$',views.SpeedDetailView.as_view(), name='speed-detail'),
]

SpeedApp/models.py
from django.db import models
from django.urls import reverse
import tensorflow as tf
from tensorflow import keras
import numpy as np
from tensorflow.keras.layers.experimental import preprocessing
import pandas as pd
from keras.models import load_model
from decimal import Decimal


class SpeedModel(models.Model):
    EngineKW  = models.DecimalField(decimal_places=5, max_digits=20)
    EngineRPM = models.DecimalField(decimal_places=5, max_digits=20)
    Horsepower = models.DecimalField(decimal_places=5, max_digits=20)
    Torque = models.DecimalField(decimal_places=5, max_digits=20)
    Speed = models.TextField()

    def get_absolute_url(self):
        return reverse('SpeedApp:speed-detail', kwargs={'pk':self.pk})


    def save(self, *args, **kwargs):
        self.calculate_speed()
        super().save(*args, **kwargs)

    def calculate_speed(self, *args, **kwargs):
        #sp = self.AbsoluteThrottlePosition + self.EngineKW + self.EngineRPM + self.FfrHour + self.FfrM + self.Torque + self.Horsepower
        #self.Speed = sp

        #data = [[self.EngineKW, self.EngineRPM, self.Torque, self.Horsepower]]
        data = np.array([[self.EngineKW, self.EngineRPM, self.Horsepower, self.Torque]]).astype('float32')
        #print(self.EngineKW, self.EngineRPM, self.Horsepower, self.Torque)
        #df = pd.DataFrame(data, columns = ['EngineKW', 'EngineRPM', 'Horsepower', 'Torque'])
        #print(df)
        #print(df.shape)
        #normalizer = preprocessing.Normalization(axis=-1)
        #normalizer.adapt(np.array(df))

        sp = load_model('dnn_model2')
        #print(sp.summary())
        result = sp.predict(data)
        self.Speed = str(result[0][0])

        

SpeedApp/forms.py
from django.forms import ModelForm
from .models import SpeedModel
from django import forms

class SpeedModelForm(ModelForm):
    class Meta:
        model = SpeedModel
        fields = ['EngineKW', 'EngineRPM','Horsepower', 'Torque']
        labels = {
        "EngineKW": "Engine kW (At the wheels)(kW)",
        "EngineRPM": "Engine RPM(rpm)",
        "Horsepower": "Horsepower (At the wheels)(hp)",
        "Torque": "Torque(Nm)"
        }
        widgets = {
        'EngineKW': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter engine kilowatts here','rows':5,}),
        'EngineRPM': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter engine RPM here','rows':5,}),
        'Horsepower': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter horsepower here','rows':5,}),
        'Torque': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter torque in NM here','rows':5,}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

HonsArtifact/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView

class HomePage(TemplateView):
    """docstring for HomePage."""
    template_name = 'index.html'
    
class InfoPage(TemplateView):
    """docstring for HomePage."""
    template_name = 'info.html'

class WorkPage(TemplateView):
    """docstring for HomePage."""
    template_name = 'work.html'

class ContactPage(TemplateView):
    """docstring for HomePage."""
    template_name = 'contact.html'

SpeedApp/views.py
#SpeedApp\views.py


from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, ListView, DeleteView
from . import forms
from . import models
# from django.shortcuts import get_object_or_404
# from django.urls import reverse_lazy
# from django.http import request

# Create your views here.
class DetectPageView(CreateView):
    form_class = forms.SpeedModelForm
    template_name = 'SpeedApp/detect.html'
    model = models.SpeedModel

class SpeedDetailView(DetailView):
    model = models.SpeedModel
    context_object_name = 'detail'
    template_name = 'SpeedApp/detail.html'

HonsArtifact/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titleblock%}{% endblock %}</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block headblock %}{% endblock %}
  </head>
<body style="background-color:#ccc5b9">
    <div>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#252422 " >
  <a class="navbar-brand" href="{% url 'home' %}" style="color:#fffcf2"><b>Speed</b>App <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
  <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
  <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
</svg></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'info' %}">Project Information</a>
          <a class="dropdown-item" href="{% url 'work' %}">How Does It Work?</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'contact' %}">Contact</a>
        </div>
      </li>
    </ul>
    
  </div>
</nav>
        
    </div>
    <div class="container">
    {% block bodyblock %}{% endblock %}
    </div>
</body>
</html>

HonsArtifact/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
  Project Info
{% endblock %}

{% block bodyblock %}
<div class="container">
<div class="container">
  <div class="jumbotron" style="background-color: #eb5e28; margin: 20px; text-align: center;">
    <h1><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-reply-all-fill" viewBox="0 0 16 16">
  <path d="M8.021 11.9 3.453 8.62a.719.719 0 0 1 0-1.238L8.021 4.1a.716.716 0 0 1 1.079.619V6c1.5 0 6 0 7 8-2.5-4.5-7-4-7-4v1.281c0 .56-.606.898-1.079.62z"/>
  <path d="M5.232 4.293a.5.5 0 0 1-.106.7L1.114 7.945a.5.5 0 0 1-.042.028.147.147 0 0 0 0 .252.503.503 0 0 1 .042.028l4.012 2.954a.5.5 0 1 1-.593.805L.539 9.073a1.147 1.147 0 0 1 0-1.946l3.994-2.94a.5.5 0 0 1 .699.106z"/>
</svg> Contact Me</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem;">
      <div class="card-header" style="text-align: center;  background-color: #403d39;"><svg style="color:#fffcf2;"xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
</svg></div>
      <div class="card-body text-dark">
        <h5 class="card-title" style="text-align: center;">LinkedIn</h5>
        <p class="card-text" style="text-align: center;">
          <a href="https://www.linkedin.com/in/marn%C3%A9-van-zyl-893b731b7/">Click Here</a>
        </p>
      </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="text-align: center;  background-color: #403d39;"><svg style="color:#fffcf2;"xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
</svg></div>
      <div class="card-body text-dark">
        <h5 class="card-title" style="text-align: center;">GitHub</h5>
        <p class="card-text" style="text-align: center;">
          <a href="https://github.com/Marne001">Click Here</a>
        </p>
      </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="text-align: center;  background-color: #403d39;"><svg style="color:#fffcf2;"xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-mailbox" viewBox="0 0 16 16">
  <path d="M4 4a3 3 0 0 0-3 3v6h6V7a3 3 0 0 0-3-3zm0-1h8a4 4 0 0 1 4 4v6a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V7a4 4 0 0 1 4-4zm2.646 1A3.99 3.99 0 0 1 8 7v6h7V7a3 3 0 0 0-3-3H6.646z"/>
  <path d="M11.793 8.5H9v-1h5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.354-.146l-.853-.854zM5 7c0 .552-.448 0-1 0s-1 .552-1 0a1 1 0 0 1 2 0z"/>
</svg></div>
      <div class="card-body text-dark">
        <h5 class="card-title" style="text-align: center;">Email</h5>
        <p class="card-text" style="text-align: center;">
         <b>marnevanzyl.work@gmail.com</b>
        </p>
      </div>
    </div>
    </div>
  </div>
</div>

</div>

{% endblock %}

HonsArtifact/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
  Home
{% endblock %}

{% block bodyblock %}<div class="container align-middle">
  <div class="jumbotron" style="background-color: #eb5e28; margin: 20px; text-align: center;">
  <img src="{% static 'boost.gif' %}" alt="Card image cap" width="150px" height="150px">
     <h1>Welcome to the Speed App</h1>
     <h6>This application can be used to detect the speed of a vehicle at a specific time according to certain parameters, by making use of machine learning and a feed-forward neural network </h6>
<a class="btn btn-outline-dark" style="margin-top: 20px"href="{% url 'SpeedApp:detect' %}">Detect Speed <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-sliders" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
</svg></a>
</div> 
{% comment %} <div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto">
            <div class="jumbotron">
                <h1>Welcome to the Speed App</h1>
   
<a class="btn btn-warning" href="{% url 'SpeedApp:detect' %}">Detect Speed <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
</svg></a>
            </div>
        </div>
    </div>
</div> {% endcomment %}

{% endblock %}

HonsArtifact/templates/info.html
{% extends 'base.html' %}
{% block titleblock %} Project Info {% endblock %}
{% block bodyblock %}

  <div class="container">
  <div
    class="jumbotron"
    style="background-color: #eb5e28; margin: 20px; text-align: center"
  >
    <h1><b><svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
</svg> Project Information</b></h1>
    <h5>Information regarding this project:</h5>
  </div>
  </div>
<div class="container">
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="background-color: #403d39;"><b style="color:#fffcf2">For What?</b></div>
      <div class="card-body text-dark">
        <h5 class="card-title" >NWU-Honours 2021</h5>
        <p class="card-text" style="background-color:#fffcf2">
          This application/program is created for my 2021-honours degree at the NWU. This project was given to us at the begining of 2021 and we had 9 months to complete it 
        </p>
      </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="background-color: #403d39;"><b style="color:#fffcf2">Title</b></div>
      <div class="card-body text-dark">
        <h5 class="card-title">Project Title</h5>
        <p class="card-text" style="background-color:#fffcf2">
           The title of this project given to me was the following: <b>Feed-forward neural network modelling of vehicle speed with onboard diagnostics</b>                             
        </p>
      </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="background-color: #403d39;"><b style="color:#fffcf2">Research Question</b></div>
      <div class="card-body text-dark">
        <h5 class="card-title">The Project Research Question</h5>
        <p class="card-text" style="background-color:#fffcf2">
          How can a feed-forward neural network alongside training data received from a vehicle's onboard diagnostics system be conducted to predict the speed of the car?
        </p>
      </div>
    </div>
    </div>
  </div>
</div>
<div>
{% comment %} Second row {% endcomment %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="background-color: #403d39;"><b style="color:#fffcf2">Description</b></div>
      <div class="card-body text-dark">
        <h5 class="card-title">The Project Description</h5>
        <p class="card-text" style="background-color:#fffcf2">
          A vehicle’s speed will be predicted by using a feed-forward neural network and a large set of training data within the project. The data will be collected by utilising an on-board diagnostics device (OBD II) and an ELM-327 dongle. After the data have been collected it will be processed to be modelled by the feed-forward neural network. The neural network will be trained to accurately predict the speed of the vehicle by using variables like engine speed, coolant temperature, engine load, selected gear, brake pedal use, and battery voltage.
        </p>
      </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="background-color: #403d39;"><b style="color:#fffcf2">Ussage</b></div>
      <div class="card-body text-dark">
        <h5 class="card-title">Possible Ussages</h5>
        <p class="card-text" style="background-color:#fffcf2">
          When using the OBD system, it is possible to collect a large quantity of data from the car, this data includes engine revolutions per minute, carbon dioxide emissions, speed, fuel usage, and engine temperature. All of this data can help optimise the efficiency of the vehicle. When the efficiency of a car is optimised people get to their destination faster and safer, there is less air pollution, and money is saved.
        </p>
      </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="card border-dark mb-3" style="max-width: 20rem">
      <div class="card-header" style="background-color: #403d39;"><b style="color:#fffcf2">Application</b></div>
      <div class="card-body text-dark">
        <h5 class="card-title">Possible applications of the program</h5>
        <p class="card-text" style="background-color:#fffcf2">
         For example, insurance companies, transport companies and department of transport. If the data is being sent to a cloud-based database and information on driver speed can be saved and monitored, insurance companies, transport companies and the department of transport can evaluate driver performance. If a driver is not reckless and drives the speed limit insurance companies can then adjust the premium for each driver according to their driving performance. The department of transport can also be able to check if drivers are driving according to the speed limit, if not it will be able to fine the drivers. Transport companies would be able to check if the drivers of the companies drive the speed limits and not reckless.
        </p>
      </div>
    </div>
    </div>
  </div>
</div>
<div>
{% endblock %}

SpeedApp/templates/SpeedApp/detect.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block titleblock%}Detect{% endblock %}
{% block headblock %}
{% endblock %}
{% block bodyblock %}


<div class="container">
  <div class="container m-5 p-3">
    <h1 style="text-align: center;"><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-speedometer" viewBox="0 0 16 16">
  <path d="M8 2a.5.5 0 0 1 .5.5V4a.5.5 0 0 1-1 0V2.5A.5.5 0 0 1 8 2zM3.732 3.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 8a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 8zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 7.31A.91.91 0 1 0 8.85 8.569l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
  <path fill-rule="evenodd" d="M6.664 15.889A8 8 0 1 1 9.336.11a8 8 0 0 1-2.672 15.78zm-4.665-4.283A11.945 11.945 0 0 1 8 10c2.186 0 4.236.585 6.001 1.606a7 7 0 1 0-12.002 0z"/>
</svg> Speed Detection</h1>
    <form method="post" class="form m-5" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form | crispy}}
      <div style="text-align: center;">
      <input type="submit" value="Calculate" class="btn" style="margin-top: 20px; background-color:#eb5e28;">
      </div>
    </form>
  </div>
</div>

{% endblock %}